# -*- coding: utf-8 -*-
"""Class#1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14BiXl20FjuvS9rbGIQUUvwh6xA610PuP
"""

import numpy as np
import pandas as pd
arr = np.array([[101,'ajay',20,'Chennai'],
                [102, 'Aman',40,'Hyderabad'],
                [103,'anta',60,'bangalur']])
print(arr)

import pandas as pd
df = pd.DataFrame(arr, columns = ['ID','name','age','city'])
print(df)

df.shape
df.size

df.columns

df['name'][0]="denash"

df['name']

df[['ID','age']]

df.iloc[1:2,:3]

df = df.assign(income=[1000,1230,2000])

df

df.set_index("ID")

df = df.assign(bonus=[200,120,500])

df

del df['bonus']

df